import 'enums.dart';

class Product {
  final int id;
  final String title;
  final String? description;
  final double price;
  final double? priceSale;
  final String preview;
  final String? promoText;
  final int popularity;
  final IntendedFor? intendedFor;
  final SkinType? skinType;
  final ProductType? productType;
  final SkinProblem? skinProblem;
  final ProductLine? productLine;
  final Effect? effect;
  final bool isCutOut;

  Product({
    required this.id,
    required this.title,
    this.description,
    required this.price,
    this.priceSale,
    required this.preview,
    this.promoText,
    required this.popularity,
    this.intendedFor,
    this.skinType,
    this.productType,
    this.skinProblem,
    this.productLine,
    this.effect,
    required this.isCutOut,
  });
}

// Placeholder product list
List<Product> sampleProducts = [
  Product(
    id: 1,
    title: "Unstress Total Serenity Serum",
    description: "",
    price: 10195,
    priceSale: -1,
    preview: "product_01.png",
    promoText: "",
    popularity: 134,
    intendedFor: IntendedFor.body,
    skinType: SkinType.normal,
    productType: ProductType.serum,
    skinProblem: SkinProblem.irritation,
    productLine: ProductLine.unstress,
    effect: Effect.antiaging,
    isCutOut: true,
  ),
  Product(
    id: 2,
    title: "Unstress Revitalizing Toner",
    description: "",
    price: 3095,
    priceSale: 1500,
    preview: "product_02.png",
    promoText: "",
    popularity: 436,
    intendedFor: IntendedFor.face,
    skinType: SkinType.dry,
    productType: ProductType.toner,
    skinProblem: SkinProblem.peeling,
    productLine: ProductLine.unstress,
    effect: Effect.moisturizing,
    isCutOut: true,
  ),
  Product(
    id: 3,
    title: "Muse Serum Supreme",
    description: "",
    price: 10195,
    priceSale: 10195,
    preview: "product_03.png",
    promoText: "",
    popularity: 623,
    intendedFor: IntendedFor.eyes,
    skinType: SkinType.oily,
    productType: ProductType.serum,
    skinProblem: SkinProblem.acne,
    productLine: ProductLine.muse,
    effect: Effect.cleansing,
    isCutOut: true,
  ),
  Product(
    id: 4,
    title: "Unstress Revitalizing Toner",
    description: "",
    price: 3195,
    priceSale: 1595,
    preview: "product_04.png",
    promoText: "1+1",
    popularity: 87,
    intendedFor: IntendedFor.face,
    skinType: SkinType.dry,
    productType: ProductType.toner,
    skinProblem: SkinProblem.wrinkles,
    productLine: ProductLine.muse,
    effect: Effect.nourishment,
    isCutOut: true,
  ),
  Product(
    id: 5,
    title: "Forever Young- Total Renewal Serum",
    description: "",
    price: 10195,
    priceSale: -1,
    preview: "product_05.png",
    promoText: "",
    popularity: 112,
    intendedFor: IntendedFor.body,
    skinType: SkinType.oily,
    productType: ProductType.serum,
    skinProblem: SkinProblem.acne,
    productLine: ProductLine.foreverYoung,
    effect: Effect.cleansing,
    isCutOut: true,
  ),
  Product(
    id: 6,
    title: "Illustious Mask",
    description: "",
    price: 1595,
    priceSale: -1,
    preview: "product_06.png",
    promoText: "",
    popularity: 34,
    intendedFor: IntendedFor.face,
    skinType: SkinType.normal,
    productType: ProductType.mask,
    skinProblem: SkinProblem.wrinkles,
    productLine: ProductLine.illustrious,
    effect: Effect.nourishment,
    isCutOut: true,
  ),
  Product(
    id: 7,
    title: "HA Eye & Neck Serum",
    description: "",
    price: 8500,
    priceSale: -1,
    preview: "product_07.png",
    promoText: "",
    popularity: 356,
    intendedFor: IntendedFor.eyes,
    skinType: SkinType.normal,
    productType: ProductType.serum,
    skinProblem: SkinProblem.wrinkles,
    productLine: ProductLine.lineRepair,
    effect: Effect.nourishment,
    isCutOut: true,
  ),
  Product(
    id: 8,
    title: "Muse nourishing cream",
    description: "",
    price: 1950,
    priceSale: -1,
    preview: "product_08.png",
    promoText: "",
    popularity: 6,
    intendedFor: IntendedFor.face,
    skinType: SkinType.normal,
    productType: ProductType.serum,
    skinProblem: SkinProblem.irritation,
    productLine: ProductLine.muse,
    effect: Effect.moisturizing,
    isCutOut: true,
  ),
  Product(
    id: 9,
    title: "Christina professional set 1",
    description: "",
    price: 7800,
    priceSale: -1,
    preview: "product_09_set.png",
    promoText: "",
    popularity: 286,
    intendedFor: IntendedFor.body,
    skinType: SkinType.normal,
    productType: ProductType.productSet,
    skinProblem: SkinProblem.peeling,
    productLine: ProductLine.muse,
    effect: Effect.antiaging,
    isCutOut: true,
  ),
  Product(
    id: 10,
    title: "Christina professional set 2",
    description: "",
    price: 9300,
    priceSale: -1,
    preview: "product_10_set.png",
    promoText: "",
    popularity: 439,
    intendedFor: IntendedFor.face,
    skinType: SkinType.combi,
    productType: ProductType.productSet,
    skinProblem: SkinProblem.acne,
    productLine: ProductLine.muse,
    effect: Effect.cleansing,
    isCutOut: false,
  ),
];
